# Generated by Django 4.1 on 2022-09-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datos_personales',
            name='usuario',
            field=models.EmailField(max_length=254),
        ),
    ]
