# Generated by Django 4.1 on 2022-09-22 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppDesafio', '0002_alter_datos_personales_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Datos_experiencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empleador', models.CharField(max_length=40)),
                ('puesto', models.CharField(max_length=40)),
                ('fechaDeinicio', models.DateField()),
                ('fechaDefin', models.IntegerField()),
            ],
        ),
    ]
